project_id = "tyiaeopcmbylgyltubni"

[functions.zapi-test]
verify_jwt = false

[functions.zapi-send]
verify_jwt = false

[functions.zapi-webhook-received]
verify_jwt = false

[functions.zapi-webhook-sent]
verify_jwt = false

[functions.zapi-register-webhooks]
verify_jwt = false

[functions.zapi-qrcode]
verify_jwt = false
