// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-conversations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-conversations.ts
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "Listar conversas",
  description: "Lista as conversas de WhatsApp da empresa do usu\xE1rio, com contato, status e \xFAltima mensagem.",
  inputSchema: {
    status: z.enum(["open", "waiting", "closed", "archived"]).optional().describe("Filtra pelo status da conversa."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de conversas (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("conversations").select(
      "id, status, sales_status, unread_count, ai_paused, ai_mode, last_message_at, created_at, contacts(name, phone, last_message_preview), departments(name)"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-conversation-messages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_conversation_messages_default = defineTool2({
  name: "get_conversation_messages",
  title: "Ler mensagens de uma conversa",
  description: "Retorna o hist\xF3rico de mensagens de uma conversa de WhatsApp, em ordem cronol\xF3gica.",
  inputSchema: {
    conversation_id: z2.string().uuid().describe("ID da conversa."),
    limit: z2.number().int().min(1).max(100).optional().describe("M\xE1ximo de mensagens (padr\xE3o 50)."),
    include_internal: z2.boolean().optional().describe("Inclui mensagens internas (padr\xE3o false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit, include_internal }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("messages").select("id, role, direction, content, message_type, media_url, delivery_status, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (!include_internal) query = query.eq("is_internal", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_contacts_default = defineTool3({
  name: "search_contacts",
  title: "Buscar contatos",
  description: "Busca contatos da empresa por nome, telefone ou e-mail.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Texto para buscar em nome, telefone ou e-mail."),
    limit: z3.number().int().min(1).max(50).optional().describe("M\xE1ximo de contatos (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("contacts").select("id, name, phone, email, tags, last_message_preview, created_at").or(`name.ilike.%${term}%,phone.ilike.%${term}%,email.ilike.%${term}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var search_knowledge_default = defineTool4({
  name: "search_knowledge",
  title: "Consultar base de conhecimento",
  description: "Busca itens indexados na base de conhecimento da empresa por t\xEDtulo ou conte\xFAdo.",
  inputSchema: {
    query: z4.string().trim().min(1).describe("Texto para buscar no t\xEDtulo ou conte\xFAdo."),
    limit: z4.number().int().min(1).max(20).optional().describe("M\xE1ximo de itens (padr\xE3o 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("knowledge_items").select("id, title, type, status, content, source_url, updated_at").eq("status", "indexed").or(`title.ilike.%${term}%,content.ilike.%${term}%`).order("updated_at", { ascending: false }).limit(limit ?? 5);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-internal-note.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var add_internal_note_default = defineTool5({
  name: "add_internal_note",
  title: "Adicionar nota interna",
  description: "Cria uma nota interna em uma conversa. A nota \xE9 vis\xEDvel apenas para a equipe e nunca \xE9 enviada ao cliente pelo WhatsApp.",
  inputSchema: {
    conversation_id: z5.string().uuid().describe("ID da conversa."),
    note_text: z5.string().trim().min(1).describe("Texto da nota interna.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, note_text }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const userId = ctx.getUserId();
    if (!userId) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: conversation, error: convError } = await supabase.from("conversations").select("id, tenant_id").eq("id", conversation_id).maybeSingle();
    if (convError) return { content: [{ type: "text", text: convError.message }], isError: true };
    if (!conversation) {
      return {
        content: [{ type: "text", text: "Conversa n\xE3o encontrada ou sem acesso." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("internal_notes").insert({
      conversation_id,
      tenant_id: conversation.tenant_id,
      user_id: userId,
      note_text
    }).select("id, note_text, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Nota interna criada (${data.id}).` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kxihlelxmsteszbecgzq";
var mcp_default = defineMcp({
  name: "remix-of-waba-flow-connect",
  title: "Remix of Waba Flow Connect",
  version: "0.1.0",
  instructions: "Ferramentas da plataforma de atendimento WhatsApp (AgentFlow). Use `list_conversations` para ver conversas, `get_conversation_messages` para ler o hist\xF3rico de uma conversa, `search_contacts` para localizar contatos, `search_knowledge` para consultar a base de conhecimento e `add_internal_note` para registrar notas internas vis\xEDveis apenas \xE0 equipe. Todo acesso respeita o isolamento por empresa (tenant) do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_conversations_default,
    get_conversation_messages_default,
    search_contacts_default,
    search_knowledge_default,
    add_internal_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
